### ISSUE TITLE
GET https://polyfill.app/api/polyfill?features=fetch,pointer-event,scroll-behavior,es net::ERR_ABORTED 500

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#24]
This suddenly started happening (again).

See this error in production:

https://app.usebubbles.com/spERuko2BEe4XM572L5KKF/comments-on-newtab/#/comment=wr6SP7h7zw1Jtef57vZhiz

<img width="1920" alt="Screen Shot 2020-10-13 at 4 29 36 PM" src="https://user-images.githubusercontent.com/331833/95926542-6b718780-0d71-11eb-8644-f4474ac92b48.png">

Our index.html:

```
<script crossorigin src="https://polyfill.app/api/polyfill?features=fetch,pointer-event,scroll-behavior,es"></script>
```

**Comment by tommedema** [comment]
@wessberg this is affecting us on production

**Comment by wessberg** [comment]
Hey there. Yeah, I'm in the middle of a host migration away from Nanobox and in that process there is some downtime while the DNS changes propagates.

**Comment by wessberg** [comment]
The host migration has finished propagating and Polyfiller has now moved away from Nanobox. Sorry for the downtime!

**Comment by tommedema** [comment]
We're seeing this now:

<img width="443" alt="Screen Shot 2020-10-13 at 6 52 41 PM" src="https://user-images.githubusercontent.com/331833/95934264-5272d180-0d85-11eb-87ad-1bad6a910261.png">

**Comment by wessberg** [comment]
The clock was passed 4AM in the morning when the host migration had finished, so I had to get some rest, but what you were seeing there appears to be because the DNS changes hadn't fully propagated, but now it should be updated everywhere now. As you know it it can take a while, several hours, for DNS resolvers across the globe to update their local cache registries.

**Comment by tommedema** [comment]
That worked, thank you. Curious if it is served from an edge CDN?

**Comment by wessberg** [comment]
It isn't, in part because Polyfiller isn't always serving static files, but sometimes are compiling bundles "Just In Time" when it discovers a new user agent it haven't seen before. But it is definitely worth looking into! Though it is important to remember that Polyfiller uses immutable cache headers, so returning visitors will always just use whatever is there in the browser cache rather than doing a network round-trip. For returning visitors, the network cost is always free.

**Comment by tommedema** [comment]
I guess the only way you could do this would be with Lambda@Edge
