### ISSUE TITLE
"Could not determine locale: No default locale has been configured" from ListFormat polyfill in Safari

### ISSUE THREAD

**Issue by kbrooks** [wessberg/Polyfiller#28]
Hey, the polyfill for Intl.ListFormat is failing on Safari v14.0. 

Repro steps:

1. Paste https://polyfill.app/api/polyfill?features=intl.list-format%7Cforce,locale=en into dev tools console on Safari
2. Type `new Intl.ListFormat('en')` in console
This will give the error
> ReferenceError: Could not determine locale: No default locale has been configured

Is this a bug in the polyfill?

**Comment by wessberg** [comment]
Hey there. You are seeing this error because you're not actually passing the `locale=en` option to the `intl` polyfill here. Notice that there's a comma

**Comment by wessberg** [comment]
Hey there. This happens because there's a comma in the URL instead of a pipe operator immediately before the `locale=en` option, which is why the option is never passed on to `intl`. The URL should be:

https://polyfill.app/api/polyfill?features=intl.list-format|force|locale=en

Let me know if that works for you 🙂

**Comment by kbrooks** [comment]
That fixes the issue, thanks
