### ISSUE TITLE
Default locale not set in Safari/Firefox for Intl polyfill

### ISSUE THREAD

**Issue by Dwyguy** [wessberg/Polyfiller#3]
I was experimenting with the Intl polyfill API, and noticed a problem when running a RelativeTimeFormat command from MDN.

Loading "https://polyfill.app/api/polyfill?features=intl.relative-time-format|force,locales=en" into my page and then running `var rtf1 = new Intl.RelativeTimeFormat('en', { style: 'narrow' });`, I receive the error "ReferenceError: Could not determine locale: No default locale has been configured". This happens in both Safari and Firefox, but not Chrome.

Am I missing a step somewhere, or is the default locale not being added?

**Comment by wessberg** [comment]
Hi there. Thanks for submitting this issue.
The issue you are experiencing is due to an error in the README. The option is actually not called `locales`, but instead `locale`. Sorry about that.

I've updated the README to reflect this.

The following query should work just fine:
```
https://polyfill.app/api/polyfill?features=intl.relative-time-format|force|locale=en
```

Please note that by applying the `force` option, you are forcing the polyfill, even if the browser already supports the feature.

Thanks for spotting this!

**Comment by Dwyguy** [comment]
Ah, foiled by the README. And yes, I was using the force option specifically to see what was loaded to try and debug. Thank you for the prompt response!
