### ISSUE TITLE
[Error] Service crashed

### ISSUE THREAD

**Issue by TechQuery** [wessberg/Polyfiller#40]
## URL

https://polyfill.app/api/polyfill?features=es.string.match-all,es.object.from-entries,regenerator-runtime,url

## Error

> An Error occurred.
> Code: 500
> ENOSPC: no space left on device, write

@wessberg

**Comment by wessberg** [comment]
Yeah, I just noticed too. I'm resizing the disk volume to increase capacity. We're back online in a few minutes

**Comment by wessberg** [comment]
The disk has been resized, but the node is under massive CPU pressure right now, so I'm considering increasing CPU capacity. On that note, please consider sponsoring this project, as I pay the infrastructure costs from my own packet, and these costs are constantly increasing.

**Comment by TechQuery** [comment]
@wessberg Thanks for your great job! I have replaced Polyfill.io with Polyfiller for almost one year.

I'm learning how to donate across Chinese Great Firewall, and making an Open-source sponsor plan in my new company.

**Comment by TechQuery** [comment]
@wessberg `502` this time

**Comment by wessberg** [comment]
Yeah, Javascript heap was exceeded due to holding over 8 gigs of polyfills in the memory cache. For now I've solved it with a simple reload, but a more sophisticated system for respecting memory- and disk limits will need to be implemented at some point to avoid exceeding available system resources. I will track this in a separate issue. Thanks for letting me know.
